/** Example column config: cars (Make, Model, Price, Year, Color, Electric, Status, Date) */

export const columnsConfig = [
  { field: 'make', headerName: 'Make', type: 'text', filter: 'text', editable: true, width: 120 },
  { field: 'model', headerName: 'Model', type: 'text', filter: 'text', editable: true, width: 120 },
  { field: 'price', headerName: 'Price', type: 'number', filter: 'number', editable: true, width: 100 },
  { field: 'year', headerName: 'Year', type: 'number', filter: 'number', editable: true, width: 80 },
  {
    field: 'color',
    headerName: 'Color',
    type: 'list',
    filter: 'list',
    editable: true,
    width: 100,
    options: ['Black', 'White', 'Silver', 'Red', 'Blue', 'Green'],
    filterOptions: { listValues: ['Black', 'White', 'Silver', 'Red', 'Blue', 'Green'] },
  },
  {
    field: 'electric',
    headerName: 'Electric',
    type: 'list',
    filter: 'list',
    editable: true,
    width: 90,
    options: ['Yes', 'No'],
    filterOptions: { listValues: ['Yes', 'No'] },
    cellStyle: (value, row) => (value === 'Yes' ? { backgroundColor: '#e8f5e9' } : {}),
  },
  {
    field: 'status',
    headerName: 'Status',
    type: 'list',
    filter: 'list',
    editable: true,
    width: 100,
    options: ['Active', 'Inactive', 'Pending'],
    filterOptions: { listValues: ['Active', 'Inactive', 'Pending'] },
    rowStyle: (row) => (row.status === 'Pending' ? { backgroundColor: '#fff3e0' } : {}),    
  },
  { field: 'date', headerName: 'Date', type: 'date', filter: 'date', editable: true, width: 120 },
];

export const columnsConfigHebrew = [
  { field: 'make', headerName: 'יצרן', type: 'text', filter: 'text', editable: true, width: 120 },
  { field: 'model', headerName: 'דגם', type: 'text', filter: 'text', editable: true, width: 120 },
  { field: 'price', headerName: 'מחיר', type: 'number', filter: 'number', editable: true, width: 100 },
  { field: 'year', headerName: 'שנה', type: 'number', filter: 'number', editable: true, width: 80 },
  {
    field: 'colorHebrew',
    headerName: 'צבע',
    type: 'list',
    filter: 'list',
    editable: true,
    width: 100,
    options: ['שחור', 'לבן', 'כסף', 'אדום', 'כחול', 'ירוק'],
    filterOptions: { listValues: ['שחור', 'לבן', 'כסף', 'אדום', 'כחול', 'ירוק'] },
  },
  {
    field: 'electricHebrew',
    headerName: 'חשמלי',
    type: 'list',
    filter: 'list',
    editable: true,
    width: 90,
    options: ['כן', 'לא'],
    filterOptions: { listValues: ['כן', 'לא'] },
    cellStyle: (value, row) => (value === 'כן' ? { backgroundColor: '#e8f5e9' } : {}),
  },
  {
    field: 'statusHebrew',
    headerName: 'סטטוס',
    type: 'list',
    filter: 'list',
    editable: true,
    width: 100,
    options: ['פעיל', 'לא פעיל', 'ממתין'],
    filterOptions: { listValues: ['פעיל', 'לא פעיל', 'ממתין'] },
    rowStyle: (row) => (row.statusHebrew === 'ממתין' ? { backgroundColor: '#fff3e0' } : {}),
  },
  { field: 'descriptionHebrew', headerName: 'תיאור', type: 'text', filter: 'text', editable: true, width: 150 },
  { field: 'date', headerName: 'תאריך', type: 'date', filter: 'date', editable: true, width: 120 },
];